### ISSUE TITLE
Deal with ES 2

### ISSUE THREAD

**Issue by sujaymansingh** [EDITD/ansible-elasticsearch_dev#1]
If we have ES 2, we need `plugin install mobz/elasticsearch-head` instead of `plugin --install mobz/elasticsearch-head`

**Comment by bobbyrenwick** [comment]
Given that this will keep happening with new versions of ES we should make our ES cluster playbook a role and use that in dev and in production.

**Comment by sujaymansingh** [comment]
That would be pretty useful!
